### PR TITLE
Fix issue with ^ and ¨

### PR DESCRIPTION
**Pull request by bluepioupiou**
fix issue #5

### CODE REVIEW

**Comment by soywod** [comment]
I will first merge #3, then I will take care of your fix. Thank you :)

**Comment by soywod** [comment]
Your fix does not seem to work for me, since I don't receive `Unidentified` but `Dead` (which refers to dead key I guess).

**Comment by bluepioupiou** [comment]
Do I add Dead to my cases and let Unidentified since this one works for me ?

**Comment by soywod** [comment]
Yes :)

**Comment by soywod** [comment]
Could you also pull? I set up git hooks to prevent pushing code with lint errors.

**Comment by bluepioupiou** [comment]
done, good idea husky

**Comment by soywod** [comment]
Still have the issue with Firefox from your branch :man_facepalming: it's a pain this issue!

image

**Comment by bluepioupiou** [comment]
Yeah, I know, I have a gift to find painful issues... sorry. Will try with FF

**Comment by bluepioupiou** [comment]
It's working for me (but was before so...) what's your OS and version of FF ?

**Comment by soywod** [comment]
`69.0.2 (64-bit)`. I think I have an idea on how to handle, I'll propose sth ASAP.

**Comment by soywod** [comment]
I pushed sth, seems to fix. I kept your idea to add `Unidentified` and `Dead` to the key stack. In fact I moved the logic from the `handleKeyDown` to the `useEffect`. Now, every key (except `Enter` and `Tab`) are sent to the stack, and processed in the `useEffect`. Thanks for your help :)

**Pull request merged**
