### PR TITLE
Pedro soaresll change tsconfig module

### PR DESCRIPTION
**Pull request by pedroSoaresll**
#20

### CODE REVIEW

**Comment by pedroSoaresll** [comment]
> Mmmh this change seems to break the cypress e2e tests, I'm investigating.

Here in localhost cypress working correctly

image

**Comment by soywod** [comment]
It was a cache issue, all is fine :+1:

**Comment by pedroSoaresll** [comment]
Waiting for the package publish. Thanks to @soywod

**Comment by soywod** [comment]
It already published ;) https://github.com/soywod/react-pin-field/issues/20#issuecomment-677789646

**Pull request merged**
